quote = "A good programmer is someone who always looks both ways before crossing a one-way street"
print("1:", quote)
print()
print("2:", quote.upper())
print()
print("3:", quote.lower())
print()
print("4:", quote.endswith("street"))
print()
print("5:", quote.isupper())
print()
print("6:", quote.upper().isupper())
print()
print("7:", quote.find("one"))
print()
print("8:", quote.replace("one", "1"))
print()
print("9:", quote.replace("one", "1").replace("both", "2"))
print()
print("10:", quote.split())
print()
print(quote)
print()
print("11: Czy jest liczbą", quote.isdigit())
print("11: Czy jest liczbą dziesiętną", quote.isdecimal())
print("12: Czy jest napisem bez cyfr", quote.isalpha())
print("13: Czy jest napisem z literami i cyframi", quote.isalnum())
